### ISSUE TITLE
Exception iterating requests!

### ISSUE THREAD

**Issue by ipa-rar** [ipa-rar/gRPC-ws#4]
https://github.com/ipa-rar/gRPC-ws/blob/0ed2fa20748ee8914a0e5e75ad1fe6e3ce1da009/bidirection_databroker/client.py#L36

Reproduce the error by  executing `bidirectional_databroker/client.py `

```
Traceback (most recent call last):
  File "client.py", line 49, in <module>
    main()
  File "client.py", line 45, in main
    bidirectional_streaming(stub)
  File "client.py", line 38, in bidirectional_streaming
    for response in response_iterator:
  File "/home/edge/.local/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/edge/.local/lib/python3.8/site-packages/grpc/_channel.py", line 809, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
>
```

**Comment by atb033** [comment]
your code works fine. you just have to run 

```
python3 server.py
```

before 

```
python3 client.py
```

**Comment by atb033** [comment]
🤦

**Comment by ipa-rar** [comment]
Does the bidirectional streaming work? I see only client streaming to server and server responds only after client streaming is complete. I think this is something related to threading.
